### ISSUE TITLE
Amazon IVS Player support 

### ISSUE THREAD

**Issue by Enigma10** [vidstack/vidstack#653] opened 2022-04-15 18:01 UTC
https://docs.aws.amazon.com/ivs/latest/userguide/player-web.html it's similar like hls. But hls is having issue with custom codecs

**Comment by mihar-22** [comment] 2023-10-02 05:03
The issue is unclear so closing it out for now. This may be something that needs to be raised in the hls.js GitHub repo.

**Closed by mihar-22** 2023-10-02 05:03 UTC
Labels: docs, provider:new
